In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(9,)

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[:, None] # Creating new axis, although its not 2D array

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
arr.reshape(-1,1) #I wamt all row elemns and one colum, same like arr[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
arr[:,np.newaxis] # Same output as arr[:, None] but arr[:, None] is not same asarr[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [12]:
arr[-1,1] # We dont have 2-D array, and we cannot slicing on col, here we are trying to fetch 2nd col which is not existed at all

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# Broacasting

In [13]:
arr1 = np.arange(9).reshape(3, 3)
arr1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr1*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [15]:
arr2 = np.random.randint(1, 5, size=(3, 3))
arr2


array([[2, 3, 4],
       [1, 2, 2],
       [4, 2, 3]])

In [16]:
arr1+arr2

array([[ 2,  4,  6],
       [ 4,  6,  7],
       [10,  9, 11]])

In [17]:
arr3 = np.random.randint(1, 5, size=(4, 3))
arr3


array([[3, 2, 2],
       [1, 1, 2],
       [4, 4, 4],
       [1, 4, 1]])

In [18]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (3,3) (4,3) 

In [19]:
arr1.shape

(3, 3)

In [20]:
arr3.shape

(4, 3)

In [21]:
arr4 = np.random.randint(1,5,(1,3))

In [22]:
arr4

array([[3, 3, 1]])

In [23]:
arr4.shape

(1, 3)

In [24]:
arr1.shape

(3, 3)

### Now lets see how broadcasting is working between arr1 and arr4

In [26]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr4

array([[3, 3, 1]])

In [25]:
arr1+arr4

array([[ 3,  4,  3],
       [ 6,  7,  6],
       [ 9, 10,  9]])

In [28]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [29]:
np.tile(a,(4,1))

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [30]:
np.tile(a,4)# If u dont give second dimension value, it prints/repeats value in 1-Dimension only

array([ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30])

In [31]:
np.tile(a,(4,2))

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [33]:
np.tile(a,(4,3))

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [34]:
a

array([ 0, 10, 20, 30])

In [36]:
b=np.arange(0,80,20)
b

array([ 0, 20, 40, 60])

In [38]:
np.sum(a+b)

180