In [33]:
! pip install numpy

You should consider upgrading via the 'C:\Users\Dell\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [34]:
import numpy as np

In [35]:

data = np.loadtxt('fitness.txt', dtype='str')


In [36]:
data[:3]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66']], dtype='<U10')

In [37]:
data.shape

(96, 7)

In [38]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [39]:
st = data[:, 1].astype('float')
st


array([5464., 6041.,   25., 5461., 6915., 4545., 4340., 1230.,   61.,
       1258., 3148., 4687., 4732., 3519., 1580., 2822.,  181., 3158.,
       4383., 3881., 4037.,  202.,  292.,  330., 2209., 4550., 4435.,
       4779., 1831., 2255.,  539., 5464., 6041., 4068., 4683., 4033.,
       6314.,  614., 3149., 4005., 4880., 4136.,  705.,  570.,  269.,
       4275., 5999., 4421., 6930., 5195.,  546.,  493.,  995., 1163.,
       6676., 3608.,  774., 1421., 4064., 2725., 5934., 1867., 3721.,
       2374., 2909., 1648.,  799., 7102., 3941., 7422.,  437., 1231.,
       1696., 4921.,  221., 6500., 3575., 4061.,  651.,  753.,  518.,
       5537., 4108., 5376., 3066.,  177.,   36.,  299., 1447., 2599.,
        702.,  133.,  153.,  500., 2127., 2203.])

In [40]:
np.mean(st)


2935.9375

In [41]:
st.min()

25.0

In [42]:
st.max()

7422.0

In [43]:
st.mean()

2935.9375

In [44]:
temp=data[:5]
temp

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

In [45]:
temp.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017'],
       ['5464', '6041', '25', '5461', '6915'],
       ['200', '100', '100', '100', '200'],
       ['181', '197', '0', '174', '223'],
       ['5', '8', '5', '4', '5'],
       ['0', '0', '0', '0', '500'],
       ['66', '66', '66', '66', '66']], dtype='<U10')

In [46]:
temp.transpose()

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017'],
       ['5464', '6041', '25', '5461', '6915'],
       ['200', '100', '100', '100', '200'],
       ['181', '197', '0', '174', '223'],
       ['5', '8', '5', '4', '5'],
       ['0', '0', '0', '0', '500'],
       ['66', '66', '66', '66', '66']], dtype='<U10')

In [47]:
date, step_count, mood, calories, hours_of_sleep, activity_status, weight = data.T

In [48]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [49]:
date.shape

(96,)

In [50]:
calories = calories.astype('int')
hours_of_sleep = hours_of_sleep.astype('int')
step_count = step_count.astype('int')

In [51]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [52]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [53]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [54]:
mood[mood == 100] = "Sad"
mood[mood == 200] = "Neutral"
mood[mood == 300] = "Happy"

C:\Users\Dell\AppData\Local\Temp\ipykernel_9304\3561189928.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mood[mood == 100] = "Sad"
C:\Users\Dell\AppData\Local\Temp\ipykernel_9304\3561189928.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mood[mood == 200] = "Neutral"
C:\Users\Dell\AppData\Local\Temp\ipykernel_9304\3561189928.py:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mood[mood == 300] = "Happy"


In [55]:
# Since all values are string, we gave as int like 100,200,300 insteadof '100'
mood[mood == '100'] = "Sad"
mood[mood == '200'] = "Neutral"
mood[mood == '300'] = "Happy"

In [56]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [57]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [58]:
np.unique(mood, return_counts=True)


(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [59]:
(mood=='Neutral').sum()

27

In [60]:
(mood=='Happy').sum()

40

In [61]:
(mood=='Sad').sum()

29

In [62]:
activity_status

array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

In [63]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [64]:
mood=='Sad'

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [65]:
(mood=='Sad').sum()

29

In [66]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [68]:
(step_count[mood=='Sad']).sum()

60989

In [69]:
step_count[mood=='Sad'].mean()


2103.0689655172414

In [70]:
step_count[mood=='Happy'].mean()


3392.725

In [71]:
mood[step_count>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [72]:
np.unique(mood[step_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [74]:
np.unique(mood[step_count<2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([13,  8, 18], dtype=int64))

In [75]:
a = np.random.randint(1, 10, size=(4, 3))
a

array([[2, 3, 6],
       [6, 5, 9],
       [7, 1, 6],
       [5, 5, 1]])

In [76]:
np.sort(a)

array([[2, 3, 6],
       [5, 6, 9],
       [1, 6, 7],
       [1, 5, 5]])

In [79]:
-np.sort(-a)#Descending order, but not prefered.

array([[6, 3, 2],
       [9, 6, 5],
       [7, 6, 1],
       [5, 5, 1]])

#  Vectorization


### In mathematics, the Euclidean distance between two points in Euclidean space is the length of a line segment between the two points.

In [80]:
pA = np.array([5,4,1,-3])
pB = np.array([6,2,3,8])


In [85]:
np.sqrt(np.sum(np.square(pA-pB)))

11.40175425099138

In [86]:
##Second way of finding Euclidiean Distance
np.sum((pA-pB)**2)**0.5

11.40175425099138

In [87]:
import math

In [88]:
math.log(10)

2.302585092994046

In [89]:
math.log(100)

4.605170185988092

In [91]:
a= np.array([6,2,5,9, 10, 3])
a

array([ 6,  2,  5,  9, 10,  3])

In [92]:
math.log(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [93]:
[math.log(t) for t in a]

[1.791759469228055,
 0.6931471805599453,
 1.6094379124341003,
 2.1972245773362196,
 2.302585092994046,
 1.0986122886681098]

In [94]:
[math.factorial(t) for t in a]

[720, 2, 120, 362880, 3628800, 6]

In [95]:
fact = np.vectorize(math.factorial)

In [96]:
a

array([ 6,  2,  5,  9, 10,  3])

In [97]:
fact(a)

array([    720,       2,     120,  362880, 3628800,       6])

In [98]:
a=np.random.randint(1,5,size=(3,3))
b=np.random.randint(1,5,size=(3,3))

In [99]:
a

array([[2, 2, 2],
       [3, 4, 2],
       [2, 4, 2]])

In [100]:
b

array([[3, 1, 1],
       [1, 4, 2],
       [2, 1, 1]])

In [101]:
a*b# This is just multiplying element wise, its not proper matrix multiplication

array([[ 6,  2,  2],
       [ 3, 16,  4],
       [ 4,  4,  2]])

In [103]:
a@b

array([[12, 12,  8],
       [17, 21, 13],
       [14, 20, 12]])

In [104]:
np.matmul(a,b)

array([[12, 12,  8],
       [17, 21, 13],
       [14, 20, 12]])

In [105]:
np.dot(a,b)

array([[12, 12,  8],
       [17, 21, 13],
       [14, 20, 12]])